package com.bibernatebeans;

// Generated 2014-12-17 11:19:13 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

	private long eventId;
	private Date eventDate;
	private String title;

	public Events() {
	}

	public Events(long eventId) {
		this.eventId = eventId;
	}

	public Events(long eventId, Date eventDate, String title) {
		this.eventId = eventId;
		this.eventDate = eventDate;
		this.title = title;
	}

	public long getEventId() {
		return this.eventId;
	}

	public void setEventId(long eventId) {
		this.eventId = eventId;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
