package com.bibernatebeans;

// Generated 2014-12-17 11:19:13 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private int newsId;
	private String newsName;
	private String newsSource;
	private String newsDetail;
	private Date newsTime;

	public News() {
	}

	public News(int newsId) {
		this.newsId = newsId;
	}

	public News(int newsId, String newsName, String newsSource,
			String newsDetail, Date newsTime) {
		this.newsId = newsId;
		this.newsName = newsName;
		this.newsSource = newsSource;
		this.newsDetail = newsDetail;
		this.newsTime = newsTime;
	}

	public int getNewsId() {
		return this.newsId;
	}

	public void setNewsId(int newsId) {
		this.newsId = newsId;
	}

	public String getNewsName() {
		return this.newsName;
	}

	public void setNewsName(String newsName) {
		this.newsName = newsName;
	}

	public String getNewsSource() {
		return this.newsSource;
	}

	public void setNewsSource(String newsSource) {
		this.newsSource = newsSource;
	}

	public String getNewsDetail() {
		return this.newsDetail;
	}

	public void setNewsDetail(String newsDetail) {
		this.newsDetail = newsDetail;
	}

	public Date getNewsTime() {
		return this.newsTime;
	}

	public void setNewsTime(Date newsTime) {
		this.newsTime = newsTime;
	}

}
