package com.bibernatebeans;

// Generated 2014-12-17 11:19:13 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int studentId;
	private String studentName;
	private Date studentBirthday;

	public Student() {
	}

	public Student(int studentId) {
		this.studentId = studentId;
	}

	public Student(int studentId, String studentName, Date studentBirthday) {
		this.studentId = studentId;
		this.studentName = studentName;
		this.studentBirthday = studentBirthday;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public Date getStudentBirthday() {
		return this.studentBirthday;
	}

	public void setStudentBirthday(Date studentBirthday) {
		this.studentBirthday = studentBirthday;
	}

}
